name: deploy

on:
  workflow_dispatch: {}
  push:
    branches: [master, main]
    paths: [dns-records.json, .github/workflows/deploy.yml]

concurrency:
  group: ${{ github.ref }}-deploy
  cancel-in-progress: false

jobs:
  check:
    name: Deploy DNS changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install DNSControl
        run: |
          curl -SsL https://github.com/StackExchange/dnscontrol/releases/download/v${VERSION}/dnscontrol-${VERSION}.amd64.deb -o ./dist.deb
          sudo dpkg -i ./dist.deb
        env:
          VERSION: 3.20.0

      - name: Create credentials file
        run: |
          echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","accountid":"$CF_ID","apitoken":"$CF_TOKEN"}}' > ./creds.json

      - run: dnscontrol push --config ./src/dns/dnsconfig.js
        env:
          CF_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_TOKEN: ${{ secrets.CF_API_TOKEN }}
