name: tests

on:
  push:
    branches: [master, main]
    tags-ignore: ['**']
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  gitleaks:
    name: GitLeaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}

      - uses: gacts/gitleaks@v1

  check:
    name: DNSControl check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gacts/install-dnscontrol@v1

      - run: dnscontrol check --config ./src/dns/dnsconfig.js

  validate-schemas:
    name: Validate schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: walbo/validate-json@v1.1.0
        with:
          schema-version: draft-07
          strict: false
          files: ./dns-records.json

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // https://octokit.github.io/rest.js/v18#activity-check-repo-is-starred-by-authenticated-user
            const star = await github.rest.activity.checkRepoIsStarredByAuthenticatedUser({
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            console.log(star)
