name: tests

on:
  push:
    branches: [master, main]
    tags-ignore: ['**']
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  gitleaks:
    name: GitLeaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}

      - uses: gacts/gitleaks@v1

  check:
    name: DNSControl check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install DNSControl
        run: |
          curl -SsL https://github.com/StackExchange/dnscontrol/releases/download/v${VERSION}/dnscontrol-${VERSION}.amd64.deb -o ./dist.deb
          sudo dpkg --force-unsafe-io -i ./dist.deb
        env:
          VERSION: 3.20.0

      - run: dnscontrol check --config ./src/dns/dnsconfig.js

  validate-schemas:
    name: Validate schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: walbo/validate-json@v1.1.0
        with:
          schema-version: draft-07
          strict: false
          files: ./dns-records.json
