name: tests

on:
  push:
    branches: [master, main]
    tags-ignore: ['**']
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs: # Docs: <https://git.io/JvxXE>
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}

      - uses: gacts/gitleaks@v1

  check:
    name: DNSControl check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: koenrh/dnscontrol-action@v3
        with:
          args: check
          config_file: ./src/dns/dnsconfig.js

  validate-schemas:
    name: Validate schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: walbo/validate-json@v1.1.0
        with:
          schema: ./dns-records.schema.json
          schema-version: draft-07
          strict: false
          files: ./dns-records.json
